import React from "react";
import useSWR from "swr";
import { useRouter } from "next/router";
import Head from "next/head";
import { Jelly } from "@uiball/loaders";
import { API_ENDPOINT } from "pages/api/anime";
import fetcher from "helper/fetcher";
import { useTheme } from "lib/zustand";
import AnimeDetailsComponent from "components/AnimeDetailsComponent";

const AnimeDetails = () => {
  const router = useRouter();
  const { animeId } = router.query;
  // https://api.jikan.moe/v4/anime/{id} -->// {"data": [{...}]}
  const { data } = useSWR(`${API_ENDPOINT}anime/${animeId}`, fetcher);

  const { theme } = useTheme();

  const { data: anime } = data || {};

  return (
    <main className="max-w-8xl mx-auto">
      <Head>
        <title>{anime?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {anime ? (
        <>
          <AnimeDetailsComponent anime={anime} />
        </>
      ) : (
        <div className="grid h-screen place-items-center">
          <Jelly color={theme} size={100} />
        </div>
      )}
    </main>
  );
};

export default AnimeDetails;
