import React from "react";
import HomeFeed from "../components/HomeFeed";
import {
  getSeasonNowAnime,
  getSeasonUpcomingAnime,
  getTopFavoritedAnime,
} from "./api/anime";
import { IMain } from "interface";
import Head from "next/head";

const HomePage = ({ seasonsNow, seasonYear, seasonsUpcoming }: IMain) => {
  const homeFeed = {
    seasonsNow,
    seasonYear,
    seasonsUpcoming,
  };
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeFeed {...homeFeed} />
    </>
  );
};

export default HomePage;

export const getStaticProps = async () => {
  const [seasonsNow, seasonYear, seasonsUpcoming] = [
    await getSeasonNowAnime(),
    await getTopFavoritedAnime(),
    await getSeasonUpcomingAnime(),
  ];

  return {
    props: {
      seasonsNow: seasonsNow || null,
      seasonYear: seasonYear || null,
      seasonsUpcoming: seasonsUpcoming || null,
    },
    revalidate: 60,
  };
};
